### ISSUE TITLE
[FEATURE REQUEST] trajectory.dat as an optional output

### ISSUE THREAD

**Issue by SimonGrall** [lorenzo-rovigatti/oxDNA#136]
**Is your feature request related to a problem? Please describe.**
I am using OxDNA to obtain the position of one specific nucleotide of a DNA strand over time, and thus throw away most of trajectory.dat. I was wondering if there was a way to do this internally, i.e. without actually writing trajectory.dat. One issue is that it fries my hard drives as I am writing/rewriting too often data that I do not use after the simulation is over.

**Describe the solution you'd like**
I want to be able to create a custom output where I only print and save the data that I need. Currently, I can do this using oxpy IN ADDITION to writing everything in trajectory.dat. I am also not sure why we have to print everything in the terminal, I may be a bit confused about the meaning of "print" in OxDNA, as it seems to both mean write in a file and print in the terminal, with no possibility of a different behavior between both.

**Describe alternatives you've considered**
I considered running the simulation in a RAM disk, which works fine, but is a problem when switching to large computation platforms.

Thank you for your help :)

**Comment by ErikPoppleton** [comment]
Hi Simon,

You can stop trajectory output by redirecting the trajectory output to `/dev/null` with `trajectory_file = /dev/null`.  Note that then you will need an [observable](https://lorenzo-rovigatti.github.io/oxDNA/observables.html#position-of-a-single-nucleotide) to keep track of the one specific nucleotide.  You can do this instead of using oxpy and will probably be a bit simpler.

Suppressing some of the logging from oxpy is something we have discussed doing, but haven't gotten around to yet.  If you want to avoid logging things to the terminal, you can redirect it to a file with `log_file = path/to/filename` in the input file.

**Comment by SimonGrall** [comment]
Hello Erik,

Thank you for your quick answer. The dev/null trick seems to be working just fine!
For the terminal logging, it seems that it would recreate my issue of writing too much things on the hard drive. 
I am far from being a programmer originally, but I was told that much of logging is possibly a very slow thing, slowing overall the simulations. Not sure how much of an impact that has but it would be nice to know.

**Comment by SimonGrall** [comment]
Just a small update on the matter. I removed the energy printout and with the dumping of trajectory.dat and energy.dat in /dev/null (replaced by my relevant observables), simulations are roughly 30% faster, everything identical aside. The terminal verbose accounted for 4% of the slowdown in my case.

**Comment by lorenzo-rovigatti** [comment]
Hi! While I think you solved your problem thanks to Erik's workaround, I'm still curious about what your issue was about. 

In principle you can effectively disable printing the trajectory by setting print_conf_interval to some huge number such as `1e20`.
As for printing to the terminal, it can be disabled altogether by setting `no_stdout_energy = true`, or again you can decrease the frequency with which it is printed by setting `print_energy_every` to a large number.

**Comment by SimonGrall** [comment]
Hello Lorenzo,

I want to follow the trajectory of only one nucleotide within a DNA strand and get the HB energy of the whole molecule without printing/writing anything else to spare my hard drive (and well, because it seems it also would be faster: if I don't use it might as well not write it).

Setting print_conf_interval to a huge number would seem to do what I want, but I was not clear whether the observables are printed if the trajectory (and/or energy for "print_energy_every") is not. It seems OxDNA documentation uses "print" to both mean printing to the terminal and writing to a file, which somehow made it confusing for me. I was afraid print_conf_interval and print_energy_every parameters would affect my observable printing frequency overwriting their own "print_every" parameter. If the observable printing frequency is independent from the rest, then your solution is indeed better. 
In any case, thank you and the other contributors for everything, OXDNA is great =)

**Comment by lorenzo-rovigatti** [comment]
Yes, `print_*` options are all independent on each other. Happy to know that the code works for you :)
I'm closing this one, but if you have any further suggestions/comments feel free to re-open the issue or make a new one.
