### ISSUE TITLE
Discussion of relaxation in documentation

### ISSUE THREAD

**Issue by rkruegs123** [lorenzo-rovigatti/oxDNA#26]
Although it has been decided that relaxation is an "art," I think that it would be valuable to provide some discussion of it in the documentation -- e.g. example input files, or example commands that override particular arguments in an input file to enable relaxation.

**Comment by RodenLuo** [comment]
While waiting for it to be in the doc, the following helped me a lot during my learning. 

[Example input files](https://github.com/lorenzo-rovigatti/oxDNA/tree/master/analysis/example_input_files)

(A few weeks ago, I found a [NEW_RELAX_PROCEDURE](https://github.com/lorenzo-rovigatti/oxDNA/tree/master/examples/NEW_RELAX_PROCEDURE). But the commit was 2 years ago. I have not yet checked the difference between these and the above though. 

**Section 3.2 Relaxation of initial geometry** of this aRxiv [pdf](https://arxiv.org/ftp/arxiv/papers/2004/2004.05052.pdf). Other sections are also good on other topics. The link given in the **Section 2.2 Files** is broken. But I somehow found this [link](https://ora.ox.ac.uk/objects/uuid:7a111527-3c1a-4c0f-af89-774b01f43abd) back then. 

These are also quite helpful in general: oxViewer and oxDNA_analysis_tools NAR [paper](https://academic.oup.com/nar/article/48/12/e72/5843822), A Primer on the oxDNA Model of DNA Frontiers [paper](https://www.frontiersin.org/articles/10.3389/fmolb.2021.693710/full), nature protocols [paper](https://www.nature.com/articles/s41596-022-00688-5).

**Comment by lorenzo-rovigatti** [comment]
I have added a page with some information. You can check it out [here](https://lorenzo-rovigatti.github.io/oxDNA/relaxation.html). Let me know what you think. Any suggestion is welcome!

**Comment by RodenLuo** [comment]
Hi Lorenzo, Thanks for putting them into the doc! It's clearer than my understanding before. But still some questions: 

For MC relaxation, I have been using [analysis/example_input_files/input_relax_MC](https://github.com/lorenzo-rovigatti/oxDNA/blob/master/analysis/example_input_files/input_relax_MC) for quite some time. Compared to the doc, the `delta_translation` and `delta_rotation` in the doc are about 5 - 10 times bigger. I guess this just means that if I stay with the example input, the movement will be smaller and the stresses are reduced slower. The `max_backbone_force = 100` in the example input vs. `max_backbone_force = 5` in the doc makes me unease. What does this entail and how should I choose? The same goes for the fact that `max_backbone_force_far` is missing in the example input. 

As for MD relaxation, I have been using [analysis/example_input_files/input_relax_MD](https://github.com/lorenzo-rovigatti/oxDNA/blob/master/analysis/example_input_files/input_relax_MD) for quite some time. I put the difference in the table below. Could you please kindly explain the differences or refer to some materials? Thanks

| Parameter                | Doc      | Example input file |
|--------------------------|----------|--------------------|
| `dt`                     | 0.002    | 0.0003             |
| `thermostat`             | langevin | bussi              |
| `diff_coeff`             | 0.5      | 2.5                |
| `max_backbone_force`     | 5        | 10                 |
| `max_backbone_force_far` | 10       | /                  |

**Comment by lorenzo-rovigatti** [comment]
Hey Roden,

the meaning of these options are explained in the [input file section](https://lorenzo-rovigatti.github.io/oxDNA/input.html) of the documentation. In general, there is no best set of options: just experiment and see what works for your particular situation. Here are some more specific answers to your queries:

* The `delta_translation` and `delta_rotation` keys control the maximum displacement for MC move. There is no definite "best value" here, but I think it makes sense to decrease the value reported in the docs to 0.1.
* The `bussi` thermostat is a bit more stable, and in fact it's a good idea to use that one instead of the langevin (I'll update the docs!).
* Using `max_backbone_force` is the maximum force that the FENE potential can exert. I wouldn't expect much difference between 5 and 10.
* `dt` is the MD time step. Lowering it may make it possible to relax very stressed configurations, at the price of longer simulations.

**Comment by RodenLuo** [comment]
Hi Lorenzo, Thanks very much! Will read more of the doc.
