### ISSUE TITLE
coil structures 

### ISSUE THREAD

**Issue by aspitaleri** [lorenzo-rovigatti/oxDNA#50]
Hi
I have been reading paper on DNA-coil structures and I notice sequence length not more than 600bp (i.e. https://academic.oup.com/nar/article/50/5/2480/6533609 and https://www.nature.com/articles/srep07655). I am wondering if you have an internal benchmark or comments on coil structures more than 2000bp. I'd like to simulate a DNA gene aroung 3500bp. How could be oxDNA simulation reliable? Thanks

ed. actually here https://www.frontiersin.org/articles/10.3389/fmolb.2021.693710/full length is longer than thousands base pair)

**Comment by lorenzo-rovigatti** [comment]
Hi,

that's a question that pertains to the model rather than the code (which is what gets discussed here). Having said that, I can say that you can surely simulate larger plectonemes since the code can easily simulate systems made up of hundreds of thousands of nucleotides. Whether doing that makes sense (i.e. can yield sensible results) will depend on the features of the system, on the wall time and on the specific things you are interested in.
