### ISSUE TITLE
[BUG] oxpy `file_info` segfaults when presented with a malformed trajectory file

### ISSUE THREAD

**Issue by JeDeveloper** [lorenzo-rovigatti/oxDNA#65]
**Describe the bug**
When given a trajectory file in which the final conf is malformed (i.e. the file is prematurely truncated), `oxDNA_analysis_tools.file_info.file_info` will crash with a segmentation fault error.
The cause of this appears to be a misalignment between the behaviors of `oxDNA_analysis_tool.UTILS.RyeReader.descibe` and `cget_confs` (which I think? is a C++ binding?). `describe` lists the index of the final, malformed conf as valid but passing it to `cget_confs` causes the segfault.

**To Reproduce**
I can reproduce the issue by mutilating my one of my other trajectories (removing the last few dozen lines), and then attempting to use `file_info` in the same manner.

**Expected behavior**
I don't think it's my place to define the failure behavior or whether it should attempt to recover but some sort of warning in this circumstance would be very helpful

**Desktop (please complete the following information):**
 - OS: Both CentOS an Ubuntu
 - oxDNA Version: latest commit ([bf8729e](https://github.com/lorenzo-rovigatti/oxDNA/commit/bf8729eb1d29a749c136eba1fd3894787a373f81))
- cmake: 3.16.3, g++9.4.0, Python 3.9.12

**Comment by ErikPoppleton** [comment]
Just wanted to let you know that I have seen this and will add a helpful error message at some point.  I'm sure that it happens because on the C side, `cget_confs` is allocating memory based on the number of bases in the first configuration and then something bad is happening when it hits a configuration with a different size.  A bit surprising it segfaults instead of leaving you with an array full of garbage data.

**Comment by ErikPoppleton** [comment]
C pointers aren't nice, but it's fixed on oat_dev now.  Will merge the pull request to master shortly.
