### ISSUE TITLE
[BUG] Installation, unable to build with make command

### ISSUE THREAD

**Issue by sheneric88** [lorenzo-rovigatti/oxDNA#84]
**Describe the bug**
I've managed to compile oxDNA into the build folder. However, when I try to build it, I get the following error/output:

Input: `mingw32-make -j4`
Output: `mingw32-make: *** No targets specified and no makefile found.  Stop.`

I am using `mingw32-make` because my current configuration of conda/Python with multiple folders added to PATH still cannot find the `make` command.

I am not too familiar with version control, so I downloaded the latest 3.6.0 release and unzipped the folder to work in there.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - oxDNA Version: Latest
- CMake: Latest
- Make: Latest MinGW and GnuWin32 both installed, unsure which is being called
- Compiler: Latest Visual Studio 2022, Windows 11 SDK and CMake modules installed

**Additional context**
I used the following compile command:
`cmake .. -DCUDA=ON -DCUDA_COMMON_ARCH=OFF -DPython=ON -DOxpySystemInstall=On`

**Comment by zoombya** [comment]
Hi, as @lorenzo-rovigatti noted you need to run the `cmake `command to configure the installation before you can run the `make`. (which looks like the source of your current errors)
I tried myself a similar setup about 4 years ago and remember running into type issues specific to `MinGW `. 
I was able to eventually compile the code, but had to hack quite a bit of code to make MinGW accept it. 
Therefore I would recommend @ErikPoppleton suggestion of using [WSL 2](https://learn.microsoft.com/en-us/windows/wsl/about)  rather than the CygWin suite.  
Its faster and allows for CUDA - GPU compilation in case your machine has an NVidia GPU.
Also I'm more likely to help you with any potential issues you might run into as this is my current setup.

**Comment by lorenzo-rovigatti** [comment]
Did you manage to compile the code?
